### ISSUE TITLE
In the same day not work

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [wernerjoss/grav-plugin-downcounter#1]
Hi @wernerjoss 

I've been testing your new plugin, and I've found an weird issue. If I choose a future hour in the same day the plugin not work fine.
For example, if I set `[downcounter due_date="2023-08-10 23:00:00"][/downcounter]`, it shows zeros in all clocks.

The caches have been cleaned before.

**Comment by wernerjoss** [comment]
Hello @pmoreno-rodriguez ,
you are right - I checked and found the same issue.
should be fixed now - please download latest version and test if it works for you.

**Comment by pmoreno-rodriguez** [comment]
Hi. Now it works fine. But I have another question: When the timer expires, shouldn't some text appear?. What is the use of the variable text defined in the plugin administration?

**Comment by wernerjoss** [comment]
Am Samstag, 12. August 2023, 19:02:17 CEST schrieb pmoreno.rodriguez:
> Hi. Now it works fine. 

ok, good.
and thanks for reporting !

> But I have another question: When the timer expires,
> shouldn't some text appear?. 

well, that could be an option.
ATM, it just stops - maybe I'll implement a message in the future...

> What is the use of the variable text defined
> in the plugin administration?

that is just a reminder from the plugin creation via devtools, has no real 
task.
I have now deleted this.

**Comment by pmoreno-rodriguez** [comment]
Thanks for your comments.
